### ISSUE TITLE
My time with OBV has come to an end (mostly ;) )

### ISSUE THREAD

**Issue by inflex** [OpenBoardView/OpenBoardView#100]
Not an issue with OBV but rather just that I need to move to new tasks/projects/goals in life.

Thank you everyone for all the contributions and helping me contribute to OBV.

**Comment by MattSturgeon** [comment]
Good luck with your endeavours and thanks for all your contributions so far!

I think it's fair to say none of us are putting in as much time to invite anymore, so don't feel bad.
