### ISSUE TITLE
Application Icon missing on OS X

### ISSUE THREAD

**Issue by RyuKojiro** [OpenBoardView/OpenBoardView#102]
20b33b10d21490eba56afe959a8443c32fd1923c breaks the application icon for OS X by moving the file in the resulting application bundle from `brd.icns` to `openboardview.icns` without updating the `Info.plist`.

**Comment by RyuKojiro** [comment]
This is fixed by PR #103

**Comment by MattSturgeon** [comment]
Oops... Good spot!
