### ISSUE TITLE
Teradyne GenCAD format

### ISSUE THREAD

**Issue by martonmiklos** [OpenBoardView/OpenBoardView#110]
I have met this format at several companies in the industry mainly used for board level debugging.
The format is text based and has accessible documentation:
http://electronix.ru/forum/index.php?act=Attach&type=post&id=15091

I am not aware of any opensource/free tools which is capable opening this format. From the proprietary tools I only know the Teradyne D2B which supports it: http://www.teradyne.com/products/production-board-test/design-to-build-d2b-software

At some point I might come up with a PR.

**Comment by martonmiklos** [comment]
Side note to myself (and might be others planning to add support for text based formats):
https://github.com/orangeduck/mpc

This library could ease the parser creation pretty much. I hope I will get some time to implement this.

**Comment by martonmiklos** [comment]
In the case if anyone would miss this I am cooking it right now here:
https://github.com/martonmiklos/OpenBoardView/tree/gencad

Basically rolls, just needs some further optimisations. (I will throw out the unused stuff from the parsing.)

**Comment by bunker-bunk567** [comment]
> In the case if anyone would miss this I am cooking it right now here:
> https://github.com/martonmiklos/OpenBoardView/tree/gencad
> 
> Basically rolls, just needs some further optimisations. (I will throw out the unused stuff from the parsing.)

why is this not being merged into main?
