### ISSUE TITLE
C++ Runtime error when open fz file

### ISSUE THREAD

**Issue by Mark-Joy** [OpenBoardView/OpenBoardView#112]
Hello I got below C++ Runtime error when open fz file. Could you help to solve the issue

![error](https://user-images.githubusercontent.com/22109528/31624170-f9574a48-b2cb-11e7-9d17-884750621985.png)

Board file and obv.conf file: 
[Schematics.zip](https://github.com/OpenBoardView/OpenBoardView/files/1388353/Schematics.zip)

Thank you!

**Comment by piernov** [comment]
I will take a look at it. In the meantime, please try with the files in the `.zip` from #10 .

**Comment by Mark-Joy** [comment]
Thank you.
I accidentally found one program can also open this fz file: http://boardviewer.net/

**Comment by piernov** [comment]
There was some special section with drawings inside this file. They are now ignored rather than parsed as parts (which caused the crash).
I don't know what they are for.

**Comment by wtangerine** [comment]
Thanks for fixing (waiting patiently for a Windows build with the fix).

It would be nice if there was a way to extract these drawings.

**Comment by piernov** [comment]
I'm gonna do a release as soon as I fix some stuff about the OpenGL version choice. For now I'll start a build on my fork: https://github.com/piernov/OpenBoardView/releases .

Yep, sadly I don't have the time to implement that right now. :(

**Comment by Mark-Joy** [comment]
Thank you for the fix. But the board is not showing correctly, it is missing most of the components. Left side is from openboardview, right size is from boardview.net

![error](https://user-images.githubusercontent.com/22109528/31835516-b99cdbd0-b586-11e7-916e-6003cedb4729.png)

**Comment by wtangerine** [comment]
Mark-Joy, you are looking at the bottom side of the board with openboardview, and at the top side with the other app.

Tested here - the pre-release version of openboardview is working correctly with your file and seems to be displaying all the components.
