### ISSUE TITLE
MinGW Runtime Assertion when opening Asus fz files

### ISSUE THREAD

**Issue by wtangerine** [OpenBoardView/OpenBoardView#114]
Tried to open 2 fz files from asus and both produce the same error.
Same result with both the release and the prerelease version from piernov's fork.

Both files open normally with the boardviewer v1.2 app.

![capture](https://user-images.githubusercontent.com/8304821/31855026-0a0fd9f8-b6ab-11e7-936e-9901e51616e7.JPG)

[Asus boardview.zip](https://github.com/OpenBoardView/OpenBoardView/files/1404391/Asus.boardview.zip)

**Comment by piernov** [comment]
Works fine here. I guess you didn't add the FZ key to OpenBoardView's configuration.

**Comment by wtangerine** [comment]
Ahhh, now I get it. Found this discussion which explains it:
https://www.badcaps.net/forum/showthread.php?p=687140

Will go try to find the key (or can someone PM me with one?).

In the meanwhile, I think it would be a good idea to handle wrong/missing key more gracefully rather than basically crash, and present some meaningful info to the user.

**Comment by piernov** [comment]
See #91 #90 #74

**Comment by wtangerine** [comment]
Yeah, this should be closed as duplicate. Thanks!
