### ISSUE TITLE
Double sided components on 7.3

### ISSUE THREAD

**Issue by f-bone** [OpenBoardView/OpenBoardView#122]
Hi guys,

how can I compile (or get a precompiled version since Im useless with coding etc) the latest pre-release which solves the double sided component view?

thank you so much,
br,
george

**Comment by piernov** [comment]
I have a build that should have the fix, dated Aug 9, 2018:
https://github.com/piernov/OpenBoardView/releases/tag/N18

One day there'll be a new official release…
