### ISSUE TITLE
Error opening a Board View

### ISSUE THREAD

**Issue by DinBan** [OpenBoardView/OpenBoardView#124]
Hello and thank you for the openboardview.
But it can't open many of BoardView *.pcb
It just says "There was an error opening file...
OpenBoardView R534, Mac OS High Sierra 10.13.4
PCB file attached.
Any solution?
Thank you in advance!
![2018-04-17 18 11 45](https://user-images.githubusercontent.com/16761196/38878962-e5a5ef34-426a-11e8-883a-17a9f614ef69.png)
"
![2018-04-17 18 14 28](https://user-images.githubusercontent.com/16761196/38879108-370260f6-426b-11e8-9c70-df33ca0ed068.png)

[iPhone6 -4.7.pcb.zip](https://github.com/OpenBoardView/OpenBoardView/files/1920443/iPhone6.-4.7.pcb.zip)

**Comment by inflex** [comment]
We have not been able to reverse engineer the format sufficiently.  Thus far no one has been able to furnish us with a specification either.

**Comment by DinBan** [comment]
#60 for Windows only....
