### ISSUE TITLE
is there a way to get it to run on a 32bit system

### ISSUE THREAD

**Issue by s4my** [OpenBoardView/OpenBoardView#127]
hi, guys i was wondering if there's a way to get openboardview run on ubuntu 32bit?

**Comment by MattSturgeon** [comment]
Do you have a compile error or something you can share? What is stopping you from building?

**Comment by MattSturgeon** [comment]
Sounds like you don't have `cmake` installed. Try `sudo apt install cmake3`

**Comment by piernov** [comment]
`cmake` is available in the official Ubuntu repository. Have you run `apt update` successfully?

**Comment by s4my** [comment]
never mind i fixed they issue, witch was that ubuntu The 17.04 repositories have been closed and withdrawn, after fixing the issue openboardview compiled completely fine. but thanks guys for trying to help.
