### ISSUE TITLE
Error on opening Asus FZ files

### ISSUE THREAD

**Issue by anshadedavana** [OpenBoardView/OpenBoardView#132]
I have a bunch of Asus board views. Most of them are in FZ format and some are in ASC format. While OpenBoardView can open and view ASC files, it is having trouble opening the FZ files. At the same time Asus 'PCB Repair Tool' program can open them so the files are not corrupted.
![error](https://user-images.githubusercontent.com/40652094/42013198-cc294970-7ab9-11e8-829d-013491febecf.png)

[boardview _ X450LC_2.0.zip](https://github.com/OpenBoardView/OpenBoardView/files/2143745/boardview._.X450LC_2.0.zip)

A sample FZ file is attached. 

Update-

I have just realized that this issue has been discussed before and it has something to do with some kind of KEY. But i don't understand what is this KEY thing really is. Any help is really appreciated.

**Comment by anshadedavana** [comment]
I am closing this issue as its a duplicate. If anyone know how to fix this key thing, please email me at anshadedavana@gmail.com

**Comment by pvtinflex** [comment]
Get the key from the IRC chat channel  irc.freenode.net #openboardview

**Comment by anshadedavana** [comment]
Hi

Got the key via IRC link. Many thanks for helping me.  Amazing software.
Loving it.
