### ISSUE TITLE
Support running on older Mac OS X versions (El Captain)

### ISSUE THREAD

**Issue by Mellodya** [OpenBoardView/OpenBoardView#147]
Dude, any chance that U can accomplish with a version of the extremly good and well know OPENBOARDVIEW for an El Captain IOS version? I'm Using your application a lot here on BRAZIL but, since I'm trting to move on, and Me and a bunch of nerds that think in the same way, are trying to use older Macbooks to help poor people to learn basic electronics with your software.

From your brazilians fans, sincerelly

**Comment by piernov** [comment]
Duplicate, see #130
