### ISSUE TITLE
build error: imgui.h: No such file or directory

### ISSUE THREAD

**Issue by Apteryks** [OpenBoardView/OpenBoardView#148]
It seems the files src/openboardview/Renderers/imgui_impl_sdl.cpp and src/openboardview/Renderers/imgui_impl_sdl_gl3.cpp should include its imgui.h header as "imgui/imgui.h" (as done everywhere else), otherwise it isn't known:

````
src/openboardview/Renderers/imgui_impl_sdl.cpp:10:19: fatal error: imgui.h: No such file or directory
````

**Comment by MattSturgeon** [comment]
How are you building obv? iirc the way CMake works, all includes should work fine because we use [`include_directories()`](https://github.com/OpenBoardView/OpenBoardView/blob/1caeb67a9f1e8bfa6fbf8496312fa1731caf335e/src/openboardview/CMakeLists.txt#L47-L58)

**Comment by piernov** [comment]
Indeed, there's no reason for this not to work. Please re-open if there's an actual issue with CMake.
