### ISSUE TITLE
Expanding to automotive circitry

### ISSUE THREAD

**Issue by merlinacious** [OpenBoardView/OpenBoardView#15]
I found this via the Louis Rossmann youtube video and was wondering if this could be expanded to a broader use case of working with electrical diagrams from say Motorcycles, Cars etc.

I don't know if those manufacturers publish .brd files but that would be an awesome application for this program.

**Comment by inflex** [comment]
I'd imagine it'd be more something up to the people who get a hold of the schem/layouts as opposed to this software?  btw, also here because of Louis :+1:

**Comment by MattSturgeon** [comment]
Since we don't know if or what files are published by the other industries, I'm adding "more info needed"

**Comment by piernov** [comment]
Closing because it's an old issue and OpenBoardView is limited to working with boardview files. If those manufacturers provide boardview files in a different format, we would be glad to implement it if you open a new issue.
