### ISSUE TITLE
feature request: copy part number/model/pin designator

### ISSUE THREAD

**Issue by raszpl** [OpenBoardView/OpenBoardView#172]
When clicking on a part there is a small annotation, often including part model/value. 
There are no key binds/mouse click options of copying part number (for example 'R100') nor  associated internal component annotation (for example '10K ohm 1/16W') :( Same for part pin designators.
Something as simple as Right clicking on Info Pane component symbol/annotation/pin designator triggering copy to clipboard would be lovely.

**Comment by piernov** [comment]
Implemented by @galkinvv in #200
