### ISSUE TITLE
Problems with compiling Paul Daniel's OBV on Mac OS Catalina

### ISSUE THREAD

**Issue by larienciel** [OpenBoardView/OpenBoardView#173]
Hi there, I can't seem to be able to make and run Paul Daniel's OBV. I am currently running it on Mac OS Catalina with homebrew installed. Please find the below the log file for your reference. 

[CMakeOutput.log](https://github.com/OpenBoardView/OpenBoardView/files/4500680/CMakeOutput.log)

Thanks.

**Comment by piernov** [comment]
Paul Daniels' OBV fork is at https://github.com/inflex/OpenBoardView , if you have an issue specifically with his fork please open the issue over there.
If the issue also affects upstream ( https://github.com/OpenBoardView/OpenBoardView , here), then it's good but please clarify.

Please attach the output on the terminal after running `./build.sh`.
