### ISSUE TITLE
Samsung CAD rendering issues — lots of parts missing

### ISSUE THREAD

**Issue by piernov** [OpenBoardView/OpenBoardView#174]
Haven't taken the time to look at this issue, but opening the attached boardview with OpenBoardView 8.0 gives this:
![Screenshot_2020-05-08_02-42-03](https://user-images.githubusercontent.com/3323883/81358079-c376d480-90d5-11ea-9432-3d253436ccad.png)
While opening with the `CAD.EXE` software gives this:
![Screenshot_2020-05-08_02-42-48](https://user-images.githubusercontent.com/3323883/81358092-cffb2d00-90d5-11ea-98c5-2e3a758f2b35.png)

Maybe something I broke during a merge.
Tagging @skvatboy , if ever he wants to take a look at it.

[BA41-02176A-Boardview.CAD.zip](https://github.com/OpenBoardView/OpenBoardView/files/4596453/BA41-02176A-Boardview.CAD.zip)

**Comment by skvatboy** [comment]
Hi Piernov 
LINE 28620-28622 has invalid character 
![Skærmbillede_2020-05-08_19-19-28](https://user-images.githubusercontent.com/5960870/81431160-fca85680-9160-11ea-80f9-9a980ba658ae.png)
It is way it failed to load the file.
I don't know what encoding to use Or is the file is corrupted ?
How do you deal with it on others file formats

**Comment by skvatboy** [comment]
Hi
I think the file corrupted, i fix the invalid character and it load.

[BA41-02176AFIXcad.zip](https://github.com/OpenBoardView/OpenBoardView/files/4605877/BA41-02176AFIXcad.zip)

**Comment by anshadedavana** [comment]
Support for Samsung CAD file is implemented in OBV ?

Release note for OBV ver 8.0 clearly says Samsung CAD is now supported but i can't open any of the Samsung boardview files in either ver 8.0 or the latest 8.95 beta release. Am i missing something here ?.

**Comment by skvatboy** [comment]
Hi anshadedavana

Maybe MattSturgeon broke during https://github.com/OpenBoardView/OpenBoardView/pull/165

Try
line 160 `valid = current_block != 0;`
To
`valid = true;`

**Comment by piernov** [comment]
Fix #206 merged, thanks for fixing the file I sent too, sorry I didn't see your answer earlier. Seems like it's all good now.
