### ISSUE TITLE
OpenBoardView-R10.1 with openboardView data support not working on Mac

### ISSUE THREAD

**Issue by hasloku** [OpenBoardView/OpenBoardView#180]
OpenBoardView-R10.1 with openboard data support will get installed on Mac without any issue.
But App is not opening at all. I am using High Sierra 10.13.6
Does anyone have the same experience??
Any solution yet??

**Comment by piernov** [comment]
This is not about the upstream version but rather @inflex fork.
Bug report opened there too: https://github.com/inflex/OpenBoardView/issues/8
Closing.
