### ISSUE TITLE
OpenBoardView issue opening .brd files

### ISSUE THREAD

**Issue by MSI78-DF** [OpenBoardView/OpenBoardView#193]
Good morning all,
I am new to OpenBordView, version 8.0.
I am already working with BoardViewer, version 1.2.0.0, which works fine.
With OpenBordView, however, I have a problem:
The software gives me an error every time I open a .brd file:
![OpenBoardView error](https://user-images.githubusercontent.com/72693569/95678408-bdc57380-0bcc-11eb-9ef9-bc4e2fed63f7.jpg)

Does anybody have any idea what's going on?
Thanks in advance !
Sincerely,

**Comment by piernov** [comment]
Hi, please try putting the file in a path without special characters (such as `é`).

**Comment by MSI78-DF** [comment]
> Hi, please try putting the file in a path without special characters (such as `é`).

piernov, you're a god ;)
IIt works perfectly! Thank you so much!

Small mistakes make big headaches... 
I wish you a great day!

Thank you all. See you soon...
