### ISSUE TITLE
Program doesn't remember user setting for View -> Show Position and Annotations

### ISSUE THREAD

**Issue by szero** [OpenBoardView/OpenBoardView#197]
All the other View settings seems to be stored properly between restarts.

**Comment by piernov** [comment]
Thanks again for the report. Fixed in 75bc1220 and e3a81797 .
I had the fix for Show Position on the `feat/board-backgroundimage` branch, so now it's applied on `master` as well.

**Comment by szero** [comment]
Thanks for quickfix again!
