### ISSUE TITLE
Add compatibility with "Honhan BoardView" files (.bdv)

### ISSUE THREAD

**Issue by stray77** [OpenBoardView/OpenBoardView#2]
https://www.deadlink.....
There's a copy of Honhan's Boardview.exe and a sample .bdv file (compal_la-5911p_r1.0_boardview.bdv).  I hope you're interested in adding compatibility with this file type as well.
Great job and thanks for your efforts.

**Comment by chloridite** [comment]
It seems Dropbox has disabled that download link.

**Comment by stray77** [comment]
[BDV-BoardView.zip](https://github.com/chloridite/OpenBoardView/files/280025/BDV-BoardView.zip)

maybe this will work? dropbox got too much traffic. lol you're too popular.

**Comment by chloridite** [comment]
Thanks, got it decrypted -- will work on integrating the format later.

[compal_la-5911p_r1.0_boardview.bdv.txt](https://github.com/chloridite/OpenBoardView/files/280100/compal_la-5911p_r1.0_boardview.bdv.txt)

**Comment by inflex** [comment]
@chloridite do you have the decoding for these two formats added yet/soon?  Thanks for doing them :+1:

**Comment by piernov** [comment]
See here: https://github.com/piernov/OpenBoardView/commits/bdv-support

**Comment by chloridite** [comment]
```go
package main

import (
	"io/ioutil"
	"os"
)

func main() {
	buf, err := ioutil.ReadFile(os.Args[1])
	if err != nil {
		panic(err)
	}
	line := 1
	for i := 0; i < len(buf); i++ {
		b := buf[i]
		if b == 0xa {
			line++
			continue
		}
		if b == 0xd && i < len(buf)-1 && buf[i+1] == 0xa {
			line++
			i++
			continue
		}
		l := int8(line % 0x7f)
		if true || b <= 0x7f {
			b = byte(0x7f - int8(b) + l + 0x20)
		} else {
			b = byte(0x7f - int8(b) + 0x20 - l)
		}
		buf[i] = b
	}
	os.Stdout.Write(buf)
}
```

**Comment by chloridite** [comment]
This is my decoder from reading the disassembled .exe -- might lead to a slightly better-looking `decode_bdv`function.

**Comment by inflex** [comment]
Are we okay to close this now?  I believe this is fully supported as far as available test files have show  as of R7.3 ?

**Comment by piernov** [comment]
I think it is too.
