### ISSUE TITLE
GLIBC_2.29' not found

### ISSUE THREAD

**Issue by sonichy** [OpenBoardView/OpenBoardView#202]
9.0-alpha1,8.90.3 (alpha3) GLIBC_2.29' not found, GLIBCXX_3.4.26 not found
8.0-1 GLIBCXX_3.4.26 not found
R7.3: Open file Boards, what is the suffix ?

**Comment by piernov** [comment]
> 9.0-alpha1,8.90.3 (alpha3) GLIBC_2.29' not found, GLIBCXX_3.4.26 not found
> 8.0-1 GLIBCXX_3.4.26 not found

These versions were built with Ubuntu 20.04 or 20.10. I will try to rebuild with Ubuntu 18.04. I don't think I will be able to support older distributions.

>  R7.3: Open file Boards, what is the suffix ?

I'm afraid I did not understand the question.

**Comment by piernov** [comment]
8.0 and 8.95.0 have been rebuilt with Ubuntu 18.04 (glibc 2.27 & GCC 7.5):
https://github.com/OpenBoardView/OpenBoardView/releases/download/8.0/openboardview_8.0-2_amd64.deb
https://github.com/OpenBoardView/OpenBoardView/releases/download/8.95.0/openboardview_8.95.0-1_amd64.deb

**Comment by sonichy** [comment]
openboardview_8.95.0-1_amd64.deb can run.
I know, open dialog, Boards -> .brd
Can you give some sample files to open ?
It can not open the file that boardviewer can open.
![alt](http://boardviewer.net/img/boardviewer.png)

**Comment by inflex** [comment]
Please attach/provide file you're trying to open

**Comment by sonichy** [comment]
[MS7740.zip](https://github.com/OpenBoardView/OpenBoardView/files/5718815/MS7740.zip)

**Comment by inflex** [comment]
I thought we had CAD support in OBV ?

I know it definitely reads in FBV ( see attached )

![s](https://user-images.githubusercontent.com/5660591/102683450-cf567780-421c-11eb-8ea0-6ddee9e508e8.jpg)

**Comment by inflex** [comment]
Just realised, this is GenCAD, and no, we don't have support for that in OBV as yet. I might migrate the FBV one over

**Comment by piernov** [comment]
OpenBoardView supports the "Samsung CAD" format, unfortunately not the GenCAD format used by MSI.
