### ISSUE TITLE
Broken link to amd64.deb on openboardview.org

### ISSUE THREAD

**Issue by 0x746b73** [OpenBoardView/OpenBoardView#204]
The link openBoardView_8.0-1_amd64.deb is broken.

The '-1' should be a '-2', i guess.

**Comment by codebio** [comment]
https://github.com/OpenBoardView/OpenBoardView/releases/download/8.0/openboardview_8.0-2_amd64.deb

**Comment by piernov** [comment]
Fixed by @inflex .
