### ISSUE TITLE
Site download link error

### ISSUE THREAD

**Issue by codebio** [OpenBoardView/OpenBoardView#213]
In your site https://openboardview.org/ the download link is: An show an 404 error
https://github.com/OpenBoardView/OpenBoardView/releases/download/8.0/openboardview_8.0-1_amd64.deb

because th correct link is:
https://github.com/OpenBoardView/OpenBoardView/releases/download/8.0/openboardview_8.0-2_amd64.deb

**Comment by piernov** [comment]
Fixed by @inflex .
