### ISSUE TITLE
8.95.1 crashing

### ISSUE THREAD

**Issue by sleeplessrazi** [OpenBoardView/OpenBoardView#216]
The latest release 8.95.1 is crashing on opening.
Mac OS Mojave 10.14.6
8.9.50 is working ok.

**Comment by piernov** [comment]
I rebuilt from 10.11. Please download again and check if it works now.

**Comment by sleeplessrazi** [comment]
Yes working now.

**Comment by sleeplessrazi** [comment]
Yes working now..
