### ISSUE TITLE
MAKE INSTALL/STRIP FAILED

### ISSUE THREAD

**Issue by dodoskyenana** [OpenBoardView/OpenBoardView#217]
![Screenshot at 2021-08-09 12-26-03](https://user-images.githubusercontent.com/27428701/128699391-274a39ac-2140-4664-966f-55d4adebcbe0.png)

**Comment by piernov** [comment]
Clone the repository with `git` instead of downloading a snapshot zip.

**Comment by dodoskyenana** [comment]
okay

**Comment by MattSturgeon** [comment]
Assuming this is resolved?
