### ISSUE TITLE
BRD not opening

### ISSUE THREAD

**Issue by SCCOBN** [OpenBoardView/OpenBoardView#225]
Yo what's up! This file is good. But it's not opening. 

https://www.upload.ee/files/13672147/NS4KU01-VA-0311-final-BRD.rar.html

**Comment by inflex** [comment]
What program are you using to view that?  It's not a Testlink/Landrex BRD file, it's "yet another" format that simply shares the BRD suffix (along with Allegro, Eagle, and Testlink)

**Comment by piernov** [comment]
This is Allegro v16, not supported by OpenBoardView. #62
