### ISSUE TITLE
i'm having this issue how do i fix it?

### ISSUE THREAD

**Issue by lucasmz1** [OpenBoardView/OpenBoardView#250]
INFO: Initializing ImGuiRendererSDLGL3
DEBUG: Could not create GL context: GLXBadFBConfig
ERROR: ImGuiRendererSDLGL3: Failed to initialize OpenGL context: Could not create GL context: GLXBadFBConfig
INFO: Initializing ImGuiRendererSDLGLES2
INFO: 
-------------------------------------------------------------
GL Vendor     : Intel Open Source Technology Center
GL GLRenderer : Mesa DRI Intel(R) HD Graphics (ILK)
GL Version    : OpenGL ES 2.0 Mesa 20.0.8
GLSL Version  : OpenGL ES GLSL ES 1.0.16
-------------------------------------------------------------
openboardview: /build/openboardview/parts/openboardview/src/src/openboardview/FileFormats/FZFile.cpp:234: FZFile::FZFile(std::vector<char>&, uint32_t*): Assertiva “content != nullptr” falhou.
Abortado (imagem do núcleo gravada)

os: ubuntu 18.04 linux notebook hp elitebook 2540p

**Comment by piernov** [comment]
https://github.com/OpenBoardView/OpenBoardView/releases/tag/9.0.3
