### ISSUE TITLE
Component and copper sides are inverted

### ISSUE THREAD

**Issue by Guimli** [OpenBoardView/OpenBoardView#254]
Hello
I converted a PCB from Kicad with KiCAD to Boardview exporter. And the boardview appears inverted in OpenBoardView. But not in other Boardview software.
[https://github.com/Guimli/Vectrex-Schematic/raw/main/LogicBoard%203GE/LogicBoard%203GE.brd](url)

**Comment by Guimli** [comment]
![OpenBoardView](https://user-images.githubusercontent.com/7476770/179516921-cfb85fcb-5703-4e17-9440-23db4fc57a01.jpg)
![BoardViewer](https://user-images.githubusercontent.com/7476770/179516942-942bb7ff-e07c-4c87-9418-8639d6a55ccf.jpg)

**Comment by piernov** [comment]
Boardview can be mirrored by pressing the `M` key or by clicking on "Mirror Board" in the "View" menu.

**Comment by sabogalc** [comment]
Hey, this issue should have been fixed with [this PR from the KiCad to Boardview exporter](https://github.com/whitequark/kicad-boardview/pull/12). Please let me know if it works now!

**Comment by Guimli** [comment]
Hello
I can confirm that an export with the latest version of KiCad to Boardview exporter fixes the problem.
Sorry to have opened the issue on OpenBoardView. It was a problem with export.
Thanks again for OpenBoardView.

**Comment by sabogalc** [comment]
> Hello I can confirm that an export with the latest version of KiCad to Boardview exporter fixes the problem. Sorry to have opened the issue on OpenBoardView. It was a problem with export. Thanks again for OpenBoardView.

That's great to hear! Since it is resolved, can you close the ticket here please?

**Comment by Guimli** [comment]
Yes
