### ISSUE TITLE
Program launches with green lines all over the UI

### ISSUE THREAD

**Issue by captainbirdy** [OpenBoardView/OpenBoardView#257]
![Screenshot (41)](https://user-images.githubusercontent.com/107886206/184685945-2fb9b36e-f77f-4f49-8705-c47e90f2e508.png)

Tried this on Window 11 Home. I've tried the latest version (9.0.3) and version 8.0. Same problem is present in both version for my system.

**Comment by piernov** [comment]
Update graphics driver.

**Comment by captainbirdy** [comment]
Will try that. Never thought of that since I've never had any problems with other games or programs I use. Thank you!
