### ISSUE TITLE
GENCAD 1.4 - Unrecognised file format

### ISSUE THREAD

**Issue by dfear** [OpenBoardView/OpenBoardView#266]
Dell latitude 3490 boardview file in  download in ".cad" format.

Opening the file results in: Unrecognised file format.

The header of the file is: 
$HEADER
GENCAD 1.4
USER "MENTOR GRAPHICS - TRANSLATOR CAMCAD Professional 4.14.312.6 - Licensed"
$ENDHEADER

[Dell LATITUDE 3490 3590 - LA-F115P - LA-F116P Boardview (.CAD).cad.zip](https://github.com/OpenBoardView/OpenBoardView/files/10105242/Dell.LATITUDE.3490.3590.-.LA-F115P.-.LA-F116P.Boardview.CAD.cad.zip)

**Comment by piernov** [comment]
GenCAD support is not available in a release yet, need to build OBV from master branch.

**Comment by piernov** [comment]
https://github.com/OpenBoardView/OpenBoardView/releases/tag/9.95.0
