### ISSUE TITLE
/usr/share/metainfo conflict

### ISSUE THREAD

**Issue by galileo-pkm** [OpenBoardView/OpenBoardView#271]
All 9.x rpm releases that I have tested (9.0.3, 9.90, 9.95) conflict with filesystem package. 
The problem is that the /usr/share/metainfo folder is allready present and owned by the filesystem package. 
This is on Fedora 37

```
[root@sol gpu]# rpm -i openboardview-9.95.0-1.x86_64.rpm
        file /usr/share/metainfo from install of openboardview-9.95.0-1.x86_64 conflicts with file from package filesystem-3.18-2.fc37.x86_64
[root@sol gpu]# 
```

**Comment by piernov** [comment]
Updated package for 9.95.0: https://github.com/OpenBoardView/OpenBoardView/releases/download/9.95.0/openboardview-9.95.0-2.x86_64.rpm
