### ISSUE TITLE
Can't open .fz, invalid fz key?

### ISSUE THREAD

**Issue by retrorepair** [OpenBoardView/OpenBoardView#275]
I have a boardview file which I know others have used but refuses to open, always just shows 0s when it errors. Please see attached. #
[ROG GL702 Boardview.zip](https://github.com/OpenBoardView/OpenBoardView/files/10887930/ROG.GL702.Boardview.zip)

**Comment by retrorepair** [comment]
I might add, regular boardview opens it fine

**Comment by inflex** [comment]
You need the FZ Decoding key.   It's not integrated in to OBV at a source level because of legal reasons.

I suspect someone will be along shortly to help you locate that.

**Comment by retrorepair** [comment]
Oh I didn't know that. Thanks for letting me know
