### ISSUE TITLE
cmake failed

### ISSUE THREAD

**Issue by Olles4** [OpenBoardView/OpenBoardView#278]
Extra flags passed to CMake: -DCMAKE_INSTALL_PREFIX=
./build.sh: line 83: cmake: command not found
CMAKE FAILED

**Comment by RobLN27** [comment]
Hey guys,
How we can fix this issue please?

Extra flags passed to CMake: -DCMAKE_INSTALL_PREFIX=
./OpenBoardView-master/build.sh: line 83: cmake: command not found
CMAKE FAILED

**Comment by piernov** [comment]
You need to install the build dependencies as indicated in the README. If you have no experience in building software from source code you should use the pre-built packages in the Releases page or from your distribution's repository.
