### ISSUE TITLE
error while building

### ISSUE THREAD

**Issue by moussatohme** [OpenBoardView/OpenBoardView#284]
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
CMake Error at src/CMakeLists.txt:62 (add_subdirectory):
  The source directory

    /Users/Moussa/Downloads/OpenBoardView-master/src/glad

  does not contain a CMakeLists.txt file.

fatal: not a git repository (or any of the parent directories): .git
-- Checking for std::filesystem
-- Checking for std::filesystem - not available, using ghc::filesystem
fatal: not a git repository (or any of the parent directories): .git
CMake Error at src/CMakeLists.txt:178 (add_subdirectory):
  The source directory

    /Users/Moussa/Downloads/OpenBoardView-master/src/filesystem

  does not contain a CMakeLists.txt file.

fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
-- Configuring incomplete, errors occurred!
CMAKE FAILED

**Comment by piernov** [comment]
Repository needs to be cloned with git as written in the README.
