### ISSUE TITLE
Part info like in BoardViewer - is it possible?

### ISSUE THREAD

**Issue by laszlo-pl** [OpenBoardView/OpenBoardView#290]
Hi,

Is it possible to display details of a selected element in OBV as I can in BoardViewer?

If not, is there a plan to include this functionality in future OBV releases?

Regards
laszlo-pl

![Screenshot 2023-05-20 211320](https://github.com/OpenBoardView/OpenBoardView/assets/134166549/56d087cd-ff65-40cc-800e-478004dae352)

**Comment by inflex** [comment]
That information is file-dependent (I'm presuming it's not a BRD file).

Do you have the example file ?

There are plans to have OpenBoardDATA support added to OBV which will provide this type of metadata too.

**Comment by laszlo-pl** [comment]
Thank you for your answer.

In the attached image you can see a comparison between BV and OBV. Specifically, what information about the element are they showing me.

I also attach the files that I used for this comparison.
[ASUS P5GC-VM.zip](https://github.com/OpenBoardView/OpenBoardView/files/11523867/ASUS.P5GC-VM.zip)
![compare](https://github.com/OpenBoardView/OpenBoardView/assets/134166549/2c749b34-3daa-4559-9e7f-4b45a2716623)

**Comment by inflex** [comment]
Thanks for that. In this case, yes, the data is contained within the parts.asc or BOM file as opposed to being available on the OBData site.   That said, most likely when the OBData extension is written this will be something that can be incorporated too.

Thanks for the sample file,  that helps a lot.

**Comment by laszlo-pl** [comment]
I am glad that I could help and look forward to further development of the program.
