### ISSUE TITLE
File .FZ

### ISSUE THREAD

**Issue by juf00th** [OpenBoardView/OpenBoardView#292]
Is support for ".FZ" files planned? If so, when?

**Comment by inflex** [comment]
Been supported right from the start almost.

You will need the key to unlock the FZ files though, something we can't povide here but should be readily available with a google.

**Comment by juf00th** [comment]
> Been supported right from the start almost.
> You will need the key to unlock the FZ files though, something we can't povide here but should be readily available with a google.

Yes, I googled some code and added it to the settings. And it works. Thank you. I understand this code can be different?

**Comment by inflex** [comment]
Sometimes there are FZ files distributed that aren't encoded, that's about the only alternative version I've found.
