### ISSUE TITLE
Problem parsing $SHAPES section when opening a GenCAD file

### ISSUE THREAD

**Issue by cyrozap** [OpenBoardView/OpenBoardView#298]
I get the following error when I try to open a certain `.cad` file:

> Failed to parse GenCAD file: the $SHAPES section was not parsed properly

The file in question can be found here:
[ASUS TUF GAMING B650-PLUS WIFI 1.04 BoardView File.zip](https://github.com/OpenBoardView/OpenBoardView/files/14329367/ASUS.TUF.GAMING.B650-PLUS.WIFI.1.04.BoardView.File.zip)

OpenBoardView version is latest from git (8528b80).

**Comment by Elextrixman** [comment]
Try this. Tested working.

[TUF GAMING B650-PLUS WIFI 1.04.cad.zip](https://github.com/OpenBoardView/OpenBoardView/files/14319805/TUF.GAMING.B650-PLUS.WIFI.1.04.cad.zip)

**Comment by Elextrixman** [comment]
Used 2.0.1.9 Beta. And it opened ok.

**Comment by Elextrixman** [comment]
Drag and drop in here
[BoardViewer.zip](https://github.com/OpenBoardView/OpenBoardView/files/14319823/BoardViewer.zip)

**Comment by swiftgeek** [comment]
That file is crashing CAMCAD (4.14.312.6), so something went horribly wrong there

**Comment by piernov** [comment]
Similar issue with this one where the `$SHAPES` section does not start with `SHAPE` but instead `INSERT`. Not sure what to do here, seems like a bogus file but if there's a tool that actually produces these maybe we should try to take it into account (but that's a pain).
[Asus_X1403ZA_BV.zip](https://github.com/OpenBoardView/OpenBoardView/files/14410392/Asus_X1403ZA_BV.zip)

**Comment by swiftgeek** [comment]
I think a conversion/repair script would be more feasible here, since those files are so deeply broken (and thus most of the contents those files can be discarded since it cannot be correlated back)

**Comment by piernov** [comment]
Workaround from 46c603c should work here as well. The original file is still a bit weird so let's hope it renders mostly fine.
