### ISSUE TITLE
Need Help, OBV keeps saying error can't open as unrecognised file format

### ISSUE THREAD

**Issue by NChilds86** [OpenBoardView/OpenBoardView#300]
So I have unsupported Mac running on Sonoma and using cli I have managed to work my way through full install and build of OBV with few slight changes in commands, moreso just adding sudo to few lines (keep in mind I am total newbie with this type of thing and git and everything Open Source so forgive me please for any silliness.

So on madcaps I downloaded following - https://www.badcaps.net/filedata/fetch?id=2059578

So I downloaded file and ended up with,
 Dell Inspiron 15 Gaming 7567 Compal LA-D993P BBV00_10 Rev1.0(A00) BoardView(.brd).rar

so I deleted the (.brd).rar

replaced with .brd saved (all done within Finder)

Go into OBV click File top left screen and clicked OPEN

then it takes me into files in Finder and I double select the file and it sends me back to OBV only to be given following error,

<img width="1268" alt="ERROR MESSAGE_OBV" src="https://github.com/OpenBoardView/OpenBoardView/assets/161984952/f342edd9-9bbd-4d4a-b74d-d92e85e4af5c">

Just to save your time the message is  ERROR OPENING FILE

Then states the path and then finishes with saying UNRECOGNISED FILE FORMAT

So then I click through few tabs and seen something about a PDF and so I thought maybe I have to change format to PDF. I change format in Finder same way as stated earlier only now with .pdf

Run it again with file - open - double click file - SAME ERROR MESSAGE and so I am stumped and given my lack of know how to get myself around on GitHub and lack of cli skill etc I am not sure what else to do but to reach out here for help from the experts.

Love your work and appreciate all the efforts to make these programs work the way they are presented. MASSIVE THANKYOU, Now just to get the front end to work for me and id be over the moon.

Many thanks in advance.

Nathan

oh I am running Sonoma 14.4.1 on mid 2014 model MacBook Pro intel i7 NVIDIA Graphics etc if this is even needed I don't know but there it is incase and as I said it is actually only supported till Big Sur which I went from Big Sur to Sonoma using the Open Core Patcher from a Git repository to run VS Code and learn other useful things and I only installed this 2 days ago and so far so good and this is the first successful application I have cloned all using just terminal so I am wrapped I got the application to boot to main screen when I clicked Return after running

 open ./openboardview.app

So I am learning and very green but not completely useless but please might need you to spell out the answers for me to get it sorted 

Cheers

**Comment by piernov** [comment]
Allegro format is not supported.  #62
