### ISSUE TITLE
Variables are shown instead of the data they're keeping

### ISSUE THREAD

**Issue by rdlf4** [OpenBoardView/OpenBoardView#304]
I'm running the latest build from this Github, I built it myself and proceeded to launch bin/openboardview. All dependencies were satisfied prior to building everything.
On Linux Mint, I keep getting these "N$" followed by a number, and I don't see how that makes any sense, so I think those are variables storing data, which isn't being displayed for some reason. Here's a screenshot:

![obv_issue](https://github.com/user-attachments/assets/32a42177-d5ba-46df-a772-31eeadee1ded)

Any help would be appreciated. Thanks in advance.

**Comment by inflex** [comment]
Those aren't variables in this instance, they're because the network-names by default from many EDA programs are set as things like $N prefix.

If you look in the file itself you'll see that they're $N... .   Until a schematic is found the network names can't be updated to "real names".
