### ISSUE TITLE
GenCad "XY html to CAD V1.2" support

### ISSUE THREAD

**Issue by moldimolt** [OpenBoardView/OpenBoardView#305]
Hello, 

OpenBoardView cannot view the attached GenCad 1.4 file, reporting it is invalid. There was a commit merged in 2023 to support these files but it seems to be broken for this file specifically on the latest stable release.

Thank you.

[GX650PI 2.0 60NR0D70-MB1020 GX650PI MB._0M_R9-7945HX__R2.0(V8G_SAMSUNG)_PERKEY_TP_PD_AERO.zip](https://github.com/user-attachments/files/16327234/GX650PI.2.0.60NR0D70-MB1020.GX650PI.MB._0M_R9-7945HX__R2.0.V8G_SAMSUNG._PERKEY_TP_PD_AERO.zip)

**Comment by piernov** [comment]
It does take a very long time to load (almost 2 minutes on my machine), I don't know why, but once it's loaded it looks ok.
OpenBoardView built from the last commit on master branch.
![screen-2024-07-22-12-14-22](https://github.com/user-attachments/assets/432e99f8-f203-4a60-bedd-215db1d6a261)

**Comment by moldimolt** [comment]
Thanks! I took another look and it seems the issue is the commit adding support was in June 2023, but there hasn't been beta or stable release since Feb 2023. I will try compiling from the latest commit.

**Comment by piernov** [comment]
Indeed, I will make another pre-release to include the bunch of GenCAD fixes and workarounds from the past year, hopefully soon.

**Comment by piernov** [comment]
Here it is: https://github.com/OpenBoardView/OpenBoardView/releases/tag/9.95.1

**Comment by moldimolt** [comment]
Thank you!

**Comment by mumu170509** [comment]
where can i download  XY html to CAD V1.2 utility
thankyou 
@moldimolt 
> Hello, 
> 
> OpenBoardView cannot view the attached GenCad 1.4 file, reporting it is invalid. There was a commit merged in 2023 to support these files but it seems to be broken for this file specifically on the latest stable release.
> 
> Thank you.
> 
> [GX650PI 2.0 60NR0D70-MB1020 GX650PI MB._0M_R9-7945HX__R2.0(V8G_SAMSUNG)_PERKEY_TP_PD_AERO.zip](https://github.com/user-attachments/files/16327234/GX650PI.2.0.60NR0D70-MB1020.GX650PI.MB._0M_R9-7945HX__R2.0.V8G_SAMSUNG._PERKEY_TP_PD_AERO.zip)
>
