### ISSUE TITLE
0.4.0 crashes, but 0.3.0 works with no problems

### ISSUE THREAD

**Issue by mark0wnik** [OpenBoardView/OpenBoardView#48]
The newest version doesn't even launch on my pc, so I decided to test out others. Installed the "error-messaging" version uploaded by you for testing in one of the previous issues, but it works fine :/ 

error it gives on launch:

> Problem Event Name: APPCRASH
>    Application Name: OpenBoardView.exe
>    Application Version: 0.0.0.0
>    Timestamp applications: 57b4bd01
>    The name of the module with an error: ucrtbase.DLL
>    The module version with the error: 10.0.10240.16390
>    The timestamp of the module with an error: 55a5bf73
>    Exception code: 40000015
>    Moving the exception: 0007d85a
>    OS Version: 6.1.7601.2.1.0.256.1
>    Locale ID 1045
>    Additional information 1: 9ea5
>    Additional Information 2: 9ea562049fa882359ac059c5ea961cfe
>    Additional Information 3: 4bcd
>    Additional Information 4: 4bcd5bfb6220f51d4d27889b0ca7459e

I bet it's some linked/not linked libraries... (previous executable - 843KB, newest - 231KB)
Please let me know If you need any specific tests/info from me.
OS Version: Win7 x64 Ultimate SP1

**Comment by piernov** [comment]
Should work with R7.3, please try it:

https://github.com/OpenBoardView/OpenBoardView/releases/tag/R7.3
