### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by katamari1992** [OpenBoardView/OpenBoardView#5]
This isn't an issue with the program but I had nowhere else to put this that I know of
How do I install this on linux?

**Comment by stray77** [comment]
install wine and try it in there.

**Comment by RavetcoFX** [comment]
You would need to compile it for linux

**Comment by drewrox2009** [comment]
can confirm, it does run in wine perfectly.

**Comment by pafmaf** [comment]
Discussed in #9.
