### ISSUE TITLE
Hi! could anybody please make an executable file for os?

### ISSUE THREAD

**Issue by kikef333** [OpenBoardView/OpenBoardView#52]
i can´t use the software and it looks great! best regards!!!

**Comment by piernov** [comment]
See https://github.com/piernov/OpenBoardView/releases/tag/N12

**Comment by inflex** [comment]
Definitely need to get those binary builds running.  Really hope we don't have to fall back to a dummy account, will defeat the purpose of having an 'organisation' if it hinders things.

**Comment by piernov** [comment]
Available as of R7.3

https://github.com/OpenBoardView/OpenBoardView/releases/tag/R7.3
