### ISSUE TITLE
0.40 CRITICAL issue. Crash on startup - 0.3 works fine

### ISSUE THREAD

**Issue by psycodeoday** [OpenBoardView/OpenBoardView#53]
after launch OpenBoardView.exe it crash suddenly (you cannot see even the main work window)
both zip/portale version and msi installer crash.
but in the same time 0.3 version (and older) works fine.

my setup:
i7, 8gb ram, gtx 980
win 7 sp1 64bit, clean, net-framework 4.6.2, java 8, eset smart security 8, fresh nvidia drivers, direct x 9.0c

![1](https://cloud.githubusercontent.com/assets/9746260/19836235/1d8999f8-9e9a-11e6-9f4a-d37ccddeb8ea.JPG)

![2](https://cloud.githubusercontent.com/assets/9746260/19836237/2215c8e8-9e9a-11e6-8538-54d03dc31f2a.JPG)

**Comment by piernov** [comment]
Try with https://github.com/piernov/OpenBoardView/releases/tag/N12

**Comment by piernov** [comment]
Should work with R7.3, please try it:

https://github.com/OpenBoardView/OpenBoardView/releases/tag/R7.3

**Comment by psycodeoday** [comment]
both versions works fine :)
thank you :)
