### ISSUE TITLE
missing version number in about seciton

### ISSUE THREAD

**Issue by psycodeoday** [OpenBoardView/OpenBoardView#54]
it will be helpful if you can add version number in about section (or on main head app name title) to help everyone recognized what version we are using.

thanks.

**Comment by piernov** [comment]
It is done already in @inflex 's fork. We just merged it back in the main repository.

**Comment by piernov** [comment]
Fixed as of R7.3, version available in Help → About.
https://github.com/OpenBoardView/OpenBoardView/releases/tag/R7.3
