### ISSUE TITLE
Mingw_Runtime_Assertion

### ISSUE THREAD

**Issue by Cinek75** [OpenBoardView/OpenBoardView#74]
Hello.
When trying to open a vinafix.vn_1000HE_MB_1.2G_boardview_encoded.fz file the openboard.exe (release R74Pre1 under Windows10 x64)program crashes and reports this message 'Mingw Runtime Assertion...".
The screenshot and the file vinafix.vn_1000HE_MB_1.2G_boardview_encoded.fz I posted in the attachment.
Greetings.
![openboardview-release_r7 4-pre1 exe- mingw_runtime_assertion](https://user-images.githubusercontent.com/13763952/26923935-f8ccec34-4c43-11e7-82bf-2a321a9aab23.png)
[vinafix.vn_1000HE_MB_1.2G_boardview_encoded.fz.zip](https://github.com/OpenBoardView/OpenBoardView/files/1060661/vinafix.vn_1000HE_MB_1.2G_boardview_encoded.fz.zip)

**Comment by piernov** [comment]
Hi,
You're probably missing the FZ decription key. You can get it on the IRC channel #openboardview@irc.freenode.net and put it in the configuration file.

We should add an explanatory message rather than a wild assert to let the user know he has to fill the key in manually.

**Comment by inflex** [comment]
Yes, agreed.  Another "small usability" item that needs to be cleaned up.  I've noticed I've run in to a couple of others lately that I need to resolve too (they're all simple, just need to be handled).

**Comment by Cinek75** [comment]
Hello.
It is working now.
I manually copied the FZ keys to the end of file "AppData \ Roaming \ OpenBoardView \ obv.conf".
Regards.
