### ISSUE TITLE
Assertion Failed when opening FZ file

### ISSUE THREAD

**Issue by portskea** [OpenBoardView/OpenBoardView#90]
![error](https://user-images.githubusercontent.com/30598373/28781879-28ef28bc-75d1-11e7-90b1-4cbf134bc1d5.PNG)

Hi!
Thank you for your program. I'm having an issue.

When trying to open a file with the `.fz` extension this error shows up:

```
"Assertion Failed", expression content != nullptr

FZFile.cpp, line 234
```

Thank You

**Comment by MattSturgeon** [comment]
Can you upload a copy of the file you were trying to use?

If you put it in a zip archive you should be able to [drag and drop](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) it into a comment here.

**Comment by piernov** [comment]
#74

**Comment by MattSturgeon** [comment]
Ah, forgot about the encryption.

I'll open a seperate issue to add a warning if the fz key is empty and close this as a duplicate.

**Comment by portskea** [comment]
File attach. Thank You!

2017-07-31 10:37 GMT-05:00 Matt Sturgeon <notifications@github.com>:

**Comment by binilj04** [comment]
For those coming here for FZ key null error:

File -> Program Preference

https://gist.github.com/binilj04/db5539574027949c1c670fba8c837b24



[source link here](https://belitong.wordpress.com/tag/openboardview/)
